name: Frontend Deploy

on:
  push:
    branches:
      - setup

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install TypeScript (if not installed)
        run: pnpm add -D typescript

      - name: Build Next.js Application
        run: pnpm run build

      - name: Transfer Files to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SERVER_KEY" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem

          # Transfer build files to server
          rsync -avz --exclude="node_modules" --exclude=".git" --delete .next package.json pnpm-lock.yaml "$SERVER_USER@$SERVER_IP:/home/$SERVER_USER/AI-Ad-Gen-Frontend-Test"

      - name: Deploy on Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key.pem "$SERVER_USER@$SERVER_IP" << EOF
            cd /home/$SERVER_USER/AI-Ad-Gen-Frontend-Test

            # Install dependencies
            pnpm install --frozen-lockfile

            # Restart the application with PM2
            pm2 delete ai-adgen-frontend || true
            pm2 start pnpm --name ai-adgen-frontend -- start
          EOF
