name: Frontend Test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # - name: Install TypeScript (if missing)
      # run: pnpm add -D typescript

      # - name: TypeScript Type Check
      # run: pnpm tsc --noEmit

      # - name: Lint Code
      # run: pnpm run lint

      # - name: Run Tests
      # run: pnpm test

      - name: Build Next.js Application
        run: pnpm run build

      - name: Debug Build Directory
        run: ls -lah && ls -lah .next || echo "⚠️ .next directory NOT found!"

      - name: Debug Build Output
        run: cat .next/build-manifest.json || echo "⚠️ No build manifest found!"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          if-no-files-found: error
